---
title: "Initial evidence on the relationship between the coronavirus pandemic and crime in the United States"
date: "2020-05-18"
---

Citation: M Ashby. 2020. Initial evidence on the relationship between the coronavirus pandemic and crime in the United States. _Crime Science_.

[Published version (open access)](https://doi.org/10.1186/s40163-020-00117-6){.btn .btn-primary}
[Preprint](https://doi.org/10.31235/osf.io/ep87s){.btn .btn-primary}
[Materials](https://osf.io/ef4dw/){.btn .btn-primary}

The COVID-19 pandemic led to substantial changes in the daily activities of millions of Americans, with many businesses and schools closed, public events cancelled and states introducing stay-at-home orders. This article used police-recorded open crime data to understand how the frequency of common types of crime changed in 16 large cities across the United States in the early months of 2020. Seasonal auto-regressive integrated moving average (SARIMA) models of crime in previous years were used to forecast the expected frequency of crime in 2020 in the absence of the pandemic. The forecasts from these models were then compared to the actual frequency of crime during the early months of the pandemic. There were no significant changes in the frequency of serious assaults in public or (contrary to the concerns of policy makers) any change to the frequency of serious assaults in residences. In some cities, there were reductions in residential burglary but little change in non-residential burglary. Thefts of motor vehicles decreased in some cities while there were diverging patterns of thefts from motor vehicles. These results are used to make suggestions for future research into the relationships between the coronavirus pandemic and different crimes.
