---
title: "Stop and Search in London: July to September 2020"
date: '2020-12-03'
---

Citation: M Ashby. _Stop and Search in London: July to September 2020_. London: Centre for Global City Policing.

[Published version (open access)](https://discovery.ucl.ac.uk/id/eprint/10115766/){.btn .btn-primary}
[Materials](https://github.com/mpjashby/stop-search-london){.btn .btn-primary}

This report summarises how police in London use their stop-and-search powers. In the period from July to September 2020, police stopped and searched 67,997 people and vehicles. The number of searches has generally increased over the past two years. 65% of searches were for drugs, with 76% of all searches resulting in no further action. Searches are heavily concentrated in some areas – half of all searches occurred in 9% of neighbourhoods.

This report was also covered in the media:

  * [Young black males in London '19 times more likely to be stopped and searched'](https://www.theguardian.com/law/2020/dec/03/young-black-males-in-london-19-times-more-likely-to-be-stopped-and-searched), *The Guardian*
  * [Black men aged 18-24 are 19 times more likely to be stopped and searched in London](https://www.voice-online.co.uk/news/uk-news/2020/12/03/black-men-aged-18-24-are-19-times-more-likely-to-be-stopped-and-searched-in-london/), *The Voice*
  * [London’s most deprived neighbourhoods see more stop and searches](https://www.ucl.ac.uk/news/2020/dec/londons-most-deprived-neighbourhoods-see-more-stop-and-searches), *UCL News*.
