---
title: "Studying crime and place with the Crime Open Database"
date: "2019-07-13"
---

Citation: M Ashby. 2019. Studying crime and place with the Crime Open Database. _Research Data Journal for the Humanities and Social Sciences_.

[Published version (open access)](https://doi.org/10.1163/24523666-00401007){.btn .btn-primary}
[Preprint](https://osf.io/preprints/socarxiv/9y7qz/){.btn .btn-primary}
[Materials](https://osf.io/qpc5v/){.btn .btn-primary}

The study of spatial and temporal crime patterns is important for both academic understanding of crime-generating processes and for policies aimed at reducing crime. However, studying crime and place is often made more difficult by restrictions on access to appropriate crime data. This means understanding of many spatio-temporal crime patterns are limited to data from a single geographic setting, and there are few attempts at replication. This article introduces the Crime Open Database (CODE), a database of 16 million offenses from 10 of the largest United States cities over 11 years and more than 60 offense types. Open crime data were obtained from each city, having been published in multiple incompatible formats. The data were processed to harmonize geographic co-ordinates, dates and times, offense categories and location types, as well as adding census and other geographic identifiers. The resulting database allows the wider study of spatio-temporal patterns of crime across multiple US cities, allowing greater understanding of variations in the relationships between crime and place across different settings, as well as facilitating replication of research.