---
title: "Police perceptions of problem-oriented policing and evidence-based policing: evidence from England and Wales"
date: "2022-03-08"
---

Citation: K Bullock, A Sidebottom, R Armitage, M Ashby, C Clemmow, S Kirby, G Laycock, N Tilley. 2022. Police perceptions of problem-oriented policing and evidence-based policing: evidence from England and Wales. _Police Practice and Research_ 23(6):775--791.

[Published version (open access)](https://doi.org/10.1080/15614263.2022.2046568){.btn .btn-primary}

The history of policing is littered with reform programmes, which aim to improve effectiveness, efficiency and legitimacy. Problem-oriented policing (POP) and evidence-based policing (EBP) are two popular and enduring reform efforts, both of which have generated significant researcher and practitioner attention. There are important similarities between POP and EBP: both approaches provide a framework intended to improve the outcomes of policing. There are also key differences, however, in terms of their main objectives, standards of evidence and units of analysis. Despite both approaches being widely advocated and implemented, presently little is known about police practitioner understanding of the relationship between POP and EBP, both in principle and in practice. To address this gap, this paper draws on survey (n = 4,141) and interview (n = 86) data collected from 19 police forces in England and Wales in 2019 to explore police practitioners’ views on the relationship between POP and EBP, and the extent to which these two approaches inform contemporary police practices. Our findings indicate that respondents generally viewed the two approaches as complementary and important frameworks for orienting police work. However, respondents also drew attention to how the two approaches are not always connected organisationally nor in the minds of police personnel. In addition, challenges were identified in the application of both approaches in practice. Our results suggest that more needs to be done to maximise the potential of POP and EBP, both separately and synergistically. The article concludes by suggesting some ways in which this might be achieved.
