---
title: "The open-access availability of criminological research to practitioners and policy makers"
date: "2020-10-21"
---

Citation: M Ashby. 2020. The open-access availability of criminological research to practitioners and policy makers. _Journal of Criminal Justice Education_ 32(1):1--21.

[Published version ($)](https://doi.org/10.1080/10511253.2020.1838588){.btn .btn-primary}
[Preprint](https://osf.io/preprints/socarxiv/wnq7h/){.btn .btn-primary}
[Postprint](/files/open_access_to_criminology_postprint.pdf){.btn .btn-primary}
[Materials](https://github.com/mpjashby/crim-oa){.btn .btn-primary}

Criminology produces policy-relevant research and criminologists often seek to influence practice, but most criminological research is confined to expensive subscription journals. This disadvantages researchers in the global south, policy makers and practitioners who have the skills to use research findings but do not have journal subscriptions. Open access seeks to increase availability of research, but take-up among criminologists has been low. 

This study used a sample of 12,541 articles published in criminology journals between 2017 and 2019 to estimate the proportion of articles available via different types of open access. Overall 22% of research was available to non-subscribers, about half that found in other disciplines, even though authors had the right to make articles open without payment in at least 95% of cases. Open access was even less common in many leading journals and among researchers in the United States.

Open access has the potential to increase access to research for those outside academia, but few scholars exercise their existing rights to distribute freely the submitted or accepted versions of their articles online. Policies to incentivise authors to make research open access where possible are needed unlock the benefits of greater access to criminological research.

