---
title: "Self-guardianship at automated teller machines"
date: "2017-01-23"
---

Citation: M Ashby, A Thorpe. 2017. Self-guardianship at automated teller machines. _Crime Prevention and Community Safety_ 19:1--16.

[Published version (open access)](http://doi.org/10.1057/s41300-016-0010-3){.btn .btn-primary}
[Postprint](https://discovery.ucl.ac.uk/id/eprint/10076716/){.btn .btn-primary}

Automated teller machines (ATMs) are central to the functioning of developed economies, but by their very nature operate without human supervision, making them vulnerable to criminal abuse. This study sought to understand how customers protect themselves from theft while using ATMs. Observations of and surveys with ATM customers were used to identify how individuals protect them- selves from theft of cash, card or personal details while using an ATM. The most common self-guardianship measure was to use only ATMs believed to be safe. The majority of customers did not cover the ATM keypad while entering their personal identification number, despite long-running publicity campaigns encouraging this behaviour. This suggests that self-guardianship is important at ATMs, but many customers fail to take even basic measures to protect themselves, their money and their bank details from theft. Banks and crime-prevention practitioners should do more to facilitate and encourage self-guardianship at ATMs.
