---
title: "Problem-oriented policing in England and Wales: barriers and facilitators"
date: "2021-12-01"
---

Citation: K Bullock, A Sidebottom, R Armitage, M Ashby, C Clemmow, S Kirby, G Laycock, N Tilley. 2021. Problem-oriented policing in England and Wales: barriers and facilitators. _Policing and Society_ 32(9):1087--1102.

[Published version (open access)](https://doi.org/10.1080/10439463.2021.2003361){.btn .btn-primary}

Evidence shows that the application of problem-oriented policing can be effective in reducing a wide range of crime and public safety issues, but that the approach is challenging to implement and sustain. This article examines police perceptions and experiences regarding organisational barriers to and facilitators of the implementation and delivery of problem-oriented policing. Drawing on surveys of (n = 4141) and interviews with (n = 86) police personnel from 19 police forces in England and Wales, we identify five key barriers and facilitators to problem-oriented policing: leadership and governance, capacity, organisational structures and infrastructure, partnership working and organisational culture. These factors provide important indicators for what police organisations need to do, or need to avoid, if they are to successfully embed and deliver problem-oriented policing. The article generates critical information about the processes that drive change in police organisations and offers recommendations for police managers who may wish to implement or develop problem-oriented policing. The paper also proposes a research agenda aimed at addressing evidence gaps in our understanding of the implementation and sustenance of problem-oriented policing.
