---
title: "Research on the Sexual Exploitation of Boys and Young Men: a UK scoping study, a summary of the findings"
date: "2014-08-01"
---

Citation: C McNaughton Nicholls, E Cockbain, H Brayley, S Harvey, C Fox, C Paskell, M Ashby, K Gibson, N Jago. 2014. _Research on the Sexual Exploitation of Boys and Young Men: a UK scoping study, a summary of the findings_. Barkingside: Barnardos.

[Published version (open access)](https://www.barnardos.org.uk/cse-young-boys-summary-report.pdf){.btn .btn-primary}

Despite growing interest in the UK and internationally in child sexual exploitation (CSE), policy-makers, practitioners, researchers and the media have tended to focus primarily on female victims. Consequently, the sexual exploitation of young males has been largely overlooked: remarkably little is known about this group, their experiences, vulnerabilities or support needs. The purpose of this document is to provide a brief synthesis of key findings from recent exploratory research on the sexual exploitation of young males in the UK.
