---
title: Alternative denominators in transport crime rates
date: "2017-11-20"
author:
  - 'R Solymosi'
  - 'MPJ Ashby'
  - 'T Cohen'
  - 'A Sidebottom'
---

[Preprint](https://osf.io/preprints/socarxiv/neaxh/){.btn .btn-primary} 
[Materials](https://osf.io/5qv38/){.btn .btn-primary}

Ensuring passenger security on mass transit is vital for modern cities. Failure to do so may jeopardize the societal, environmental and health benefits of public transportation. One challenge with securing transit environments comes from the difficulty of accurately estimating the risk of criminal victimization at various nodes, particularly with respect to the choice of denominator that most reliably captures variations in the number of opportunities for different crime types. In this paper, we draw on open-source data as denominators for calculating the risk of violent crime on London Underground. We argue that denominator choice can depend on the ease of availability, accuracy and applicability of the data required, and demonstrate how the choice of denominator significantly affects estimations of crime risk. We make recommendations for research, policy and practice in denominator choice, and finally integrate the results to develop a taxonomy of London Underground stations based on their risk profiles across all measures.

