---
title: "Changes in Police Calls for Service During the Early Months of the 2020 Coronavirus Pandemic"
date: "2020-06-25"
---

Citation: M Ashby. 2020. Changes in Police Calls for Service During the Early Months of the 2020 Coronavirus Pandemic. _Policing: a journal of policy and practice_ 14(4):1054--1072.

[Published version (open access)](https://doi.org/10.1093/police/paaa037){.btn .btn-primary}
[Preprint](https://doi.org/10.31235/osf.io/h4mcu){.btn .btn-primary}
[Materials](https://osf.io/7v3nu/){.btn .btn-primary}

The coronavirus pandemic poses multiple challenges for policing, including the need to continue responding to calls from the public. Several contingency plans warned police to expect a large and potentially overwhelming increase in demand from the public during a pandemic, but (to the author’s knowledge) there is no empirical work on police demand during a major public health emergency. This study used calls-for-service data from 10 large cities in the USA to analyse how calls for service changed during the early months of the 2020 COVID-19 outbreak, compared to forecasts of call volume based on data from previous years. Contrary to previous warnings, overall the number of calls went down during the early weeks of the pandemic. There were substantial reductions in specific call types, such as traffic collisions, and significant increases in others, such as calls to dead bodies. Other types of calls, particularly those relating to crime and order maintenance, continued largely as before. Changes in the frequency of different call types present challenges to law enforcement agencies, particularly since many will themselves be suffering from reduced staffing due to the pandemic. Understanding changes to calls in detail will allow police leaders to put in place evidence-based plans to ensure they can continue to serve the public.

