---
title: "Not just a girl thing: a large-scale comparison of male and female users of child sexual exploitation services in the UK"
date: "2014-08-01"
---

Citation: E Cockbain, H Brayley, M Ashby. 2014. _Not just a girl thing: a large-scale comparison of male and female users of child sexual exploitation services in the UK_. Report for Barnardos.

[Published version (open access)](http://www.barnardos.org.uk/resources/research_and_publications/not-just-a-girl-thing/publication-view.jsp?pid=PUB-2802){.btn .btn-primary}

Child sexual exploitation (CSE) is increasingly recognised in the UK and internationally as a child protection and crime prevention priority. Yet, research and responses have focused heavily on girls and young women, leaving fundamental knowledge gaps around the characteristics and needs of boys and young men affected by CSE. The study introduced in this document formed part of a wider collaborative research programme designed to improve understanding of and inform responses to the sexual exploitation of boys and young men in the UK.

