---
title: "Using crime science for understanding and preventing theft of metal from the British railway network"
date: "2016-08-28"
---

Citation: M Ashby. 2016. _Using crime science for understanding and preventing theft of metal from the British railway network_. PhD thesis.

[Published version (open access)](http://discovery.ucl.ac.uk/1507833/){.btn .btn-primary}

Metal theft has emerged as a substantial crime problem, causing widespread disruption and damage in addition to the loss of metal itself, but has been the subject of little research. This thesis uses the paradigm of crime science to analyse the problem, focusing on thefts from the railway network in Great Britain. Two theoretical concepts are used: crime scripts and the routine-activities approach. Police-recorded crime and intelligence data are used to develop a crime script, which in turn is used to identify features of the problem a) analysis of which would potentially be useful to practitioners seeking to understand and prevent metal theft, and b) for which sufficient data are available to make analysis practical. Three such features are then analysed in more detail. First, spatial and temporal distributions of metal theft are analysed. Metal theft appears to differ from other types of acquisitive crime in ways potentially useful for prevention, for example in clustering outside (but close to) cities, and in exhibiting significant repeat victimisation over a longer period than found for other crimes. Second, the potential crime-prevention value of the market-reduction approach is analysed by testing for clusters of thefts close to the locations of scrap-metal dealers. Scrap-yard locations are found to be a significant predictor of local thefts, controlling for metal availability, area accessibility, and density of population and industry. Third, the involvement of organised crime groups (OCGs) in metal theft is tested. Due to the difficulty of defining and measuring organised crime, multiple approaches are used: all show OCG involvement to be rarer than official estimates previously suggested. The implications of these findings for practitioners are discussed. The thesis also considers the relevance of the results for the use of crime science and the analysis of OCGs.
