---
title: "Implementing and sustaining problem-oriented policing: a guide"
date: "2020-03-01"
---

Citation: A Sidebottom, S Kirby, N Tilley, R Armitage, M Ashby, K Bullock, G Laycock. 2020. _Implementing and sustaining problem-oriented policing: a guide_. College of Policing.

[Published version (open access)](https://discovery.ucl.ac.uk/id/eprint/10093611/){.btn .btn-primary}

This guide is about embedding POP in your organisation. It is written primarily for senior officers and managers and is intended to complement a sister guide on problem-solving in practice. This guide is not a step-by-step manual - there is no single road to or recipe for implementing POP. Instead, what follows is a review of what is known about implementing and sustaining POP, with recommended resources provided at the end. The guide has three parts. The first part outlines the core features of POP. The second part makes the business case for POP as an operating model for contemporary policing. The third part discusses three conditions conducive to the successful implementation of POP – leadership, understanding and infrastructure – and provides examples of good and poor practice. The guide ends with a self-assessment tool to help you determine your organisation’s readiness for and progress in implementing POP.
