---
title: "Problem-Oriented Policing in England and Wales in 2019"
date: "2020-03-01"
---

Citation: A Sidebottom, K Bullock, R Armitage, M Ashby, C Clemmow, S Kirby, G Laycock, N Tilley. 2020. _Problem-Oriented Policing in England and Wales in 2019_. London: College of Policing.

[Published version (open access)](https://discovery.ucl.ac.uk/id/eprint/10094764/){.btn .btn-primary}
[Project](https://whatworks.college.police.uk/About/News/Pages/POP.aspx){.btn .btn-primary}

This report describes the ‘state of the art’ in respect to problem-solving in England and Wales in 2019. It also draws on previous research to examine changes and continuities in police problem-solving over time. The findings in this report are intended to act as a baseline against which the longer-term impact of the PSDRP could be measured. They also provide insights to police forces seeking to better implement, embed and advance a problem-oriented approach. This report draws on data collected from twenty of the forty-three territorial police forces in England and Wales. Eight of the twenty police forces were selected purposefully to ensure adequate representation of forces with different histories of and experience in POP. A further twelve police forces were selected at random. Data were collected in three main ways: (1) a cross-sectional online anonymous survey distributed to all police officers and staff in nineteen police forces (n = 4,141); (2) content analysis of problem-solving documents supplied by fourteen police forces (n = 77); and (3) semi-structured individual interviews with police officers and staff identified as being knowledgeable about problem-solving in the eight purposefully selected police forces, as well as a selection of individuals identified through snowball sampling and those associated with the PSDRP (n = 111). These data were supplemented with a systematic assessment of the 71 submissions to the 2018/19 Tilley Award, an annual award that recognises excellence in problem-solving in the UK.
