---
title: "Problem solving for (crime) prevention"
date: '2025-10-13'
---

Presentation to senior leaders from Durham Constabulary on using problem-solving (problem-oriented policing) techniques to reduce crime.

[**Presentation slides** (Powerpoint)](/slides/durham_pop_2025.pptx)

Resources mentioned in the presentation:

  * [College of Policing Crime Reduction Toolkit](https://www.college.police.uk/research/crime-reduction-toolkit).
  * [Arizona State University Center for Problem-Oriented Policing](https://popcenter.asu.edu/).
  * [*Practical Psychology for Policing*](https://policy.bristoluniversitypress.co.uk/practical-psychology-for-policing) by Prof Jason Roach.


Useful free resources on police problem solving:

  * [_Problem Solving for Neighbourhood Policing_](https://discovery.ucl.ac.uk/1393275/) a short guide to problem solving aimed at frontline officers and staff, especially those on neighbourhood teams.
  * [_Successful Police Problem-Solving: a practice guide_](https://discovery.ucl.ac.uk/10093612/) a more-detailed guide published by the College of Policing that provides tips for effectively using problem-solving techniques to produce sustainable reductions in crime. This guide is aimed mainly a frontline officers/staff and their immediate managers.
  * [_Implementing and Sustaining Problem-Oriented Policing: a guide_](https://discovery.ucl.ac.uk/10093611/) a companion guide aimed at police leaders detailing how to create an environment where officers and staff can effectively use problem-solving techniques.
