---
title: "Routine activities and proactive police activity: a macro-scale analysis of police searches in London and New York City"
date: "2015-11-09"
---

Citation: M Ashby, L Tompson. 2015. Routine activities and proactive police activity: a macro-scale analysis of police searches in London and New York City. _Justice Quarterly_ 34:109--135.

[Published version (open access)](https://doi.org/10.1080/07418825.2015.1103380){.btn .btn-primary}

This paper explored how city-level changes in routine activities were associated with changes in frequencies of police searches using six years of police records from the London Metropolitan Police Service and the New York City Police Department. Routine activities were operationalised through selecting events that potentially impacted on (a) the street population, (b) the frequency of crime or (c) the level of police activity. OLS regression results indicated that routine activity variables (e.g. day of the week, periods of high demand for police service) can explain a large proportion of the variance in search frequency throughout the year. A complex set of results emerged, revealing cross-national dissimilarities and the differential impact of certain activities (e.g. public holidays). Importantly, temporal frequencies in searches are not reducible to associations between searches and recorded street crime, nor changes in on-street population. Based on the routine activity approach, a theoretical police-action model is proposed.
