---
title: "Is there more violence around schools? Four tests across nine cities"
date: "2019-03-26"
---

Citation: M Ashby. 2019. Is there more violence around schools? Four tests across nine cities. Pre-print.

[Preprint](https://osf.io/preprints/socarxiv/sg2qt/){.btn .btn-primary}
[Materials](https://osf.io/ah9sz/){.btn .btn-primary}

Objectives: Research evidence on schools as a factor in the distribution of neighborhood violence has produced varying and at-times directly contradictory results. Drawing conclusions from existing research is also complicated by data limitations and methodological differences. The present study sought to further research in this area using a novel open-data source.

Methods: Police-recorded assault and personal robbery data from nine large US cities were used to test four hypotheses (derived from the routine activities approach) on spatio-temporal patterns of violence around schools. Multi-level Markov Chain Monte Carlo models were used to reflect the clustered structure of the data.

Results: The presence of a public secondary (middle or high) school in a census block group was associated with higher daytime assault and robbery counts on weekdays when schools were in session but not on non-school weekdays, and the effect was larger for larger schools. No such relationships were found for elementary schools. However, there were variations between cities, in that there was no effect in one city and the effect sizes in other cities varied substantially.

Conclusions: The results were consistent with the routine activites approach, suggesting a role for middle and high schools in the distribution of neighbourhood violence. The differences between cities suggest that studying multiple cities is important in the investigation of crime and place, and that open data may provide a mechanism for overcoming the data-access difficulties that have previously limited multi-city studies of spatio-temporal variations in crime.
