---
title: "Comparing methods for measuring crime harm/severity"
date: "2017-08-23"
---

Citation: M Ashby. Comparing methods for measuring crime harm/severity. _Policing: A Journal of Policy and Practice_ 12(4):439--454.

[Published version ($)](https://doi.org/10.1093/police/pax049){.btn .btn-primary}
[Preprint](https://osf.io/preprints/socarxiv/23nv7){.btn .btn-primary}
[Materials](https://osf.io/c8dx4/){.btn .btn-primary}

Ensuring police resources are focused where they are most needed requires understanding of the consequences of crime in relation to offenders, victims, and places. Most crime analysis is based on counts of crimes, but not all crimes are equivalent to one another. Researchers have recently developed two methods—the Crime Harm Index and the Crime Severity Score—for weighting crime counts according to the severity of different crime types. This article compares these two methods by applying them to two common crime-analysis scenarios: focusing resources on the most-important types of crime and in the areas most affected by crime. The two measures are found to produce substantially different results when other factors are held constant. The results of severity-weighted crime analysis (and the decision made based on them) could therefore be greatly influenced by the method chosen. The implications of this are discussed and future research avenues outlined.

