---
title: "Police practitioner views on the challenges of analysing and responding to knife crime"
date: "2023-02-02"
---

Citation: K Bullock, I Agar, M Ashby, I Brennan, G Hales, A Sidebottom, N Tilley. 2023. Police practitioner views on the challenges of analysing and responding to knife crime. _Crime Science_ 12(1). 

[Published version (open access)](https://doi.org/10.1186/s40163-022-00180-1){.btn .btn-primary}

Knife crime remains a major concern in England and Wales. Problem-oriented and public health approaches to tackling knife crime have been widely advocated, but little is known about how these approaches are understood and implemented by police practitioners. To address this knowledge gap, this article draws on semi-structured interviews and focus groups with 44 police personnel to consider the processes and challenges of applying problem-oriented and public health approaches to knife crime. Findings show that knife crime was seen as a complex social problem which would not be solved by ‘silver bullets’; prevention was prioritised and the limitations of enforcement were widely acknowledged; there was an emphasis on understanding and responding to vulnerability and risk; discussion of ‘holistic’ and ‘whole systems’ approaches was evident (but these concepts were rarely defined); and the problem of serious violence was viewed as a shared, multi-agency issue that the police could not tackle alone. Various challenges were also evident, most notably around analysis of the drivers and patterns of knife crime and the evaluation of knife crime interventions. The article concludes by discussing the implications of the findings for knife crime prevention and the implementation and advancement of problem-oriented and public health approaches to policing.

