---
title: "Copper cable theft: revisiting the price–theft hypothesis"
date: "2014-03-14"
---

Citation: A Sidebottom, M Ashby, S Johnson. 2014. Copper cable theft: revisiting the price–theft hypothesis. _Journal of Research in Crime and Delinquency_ 51(5):684--700.

[Published version ($)](https://doi.org/10.1177/0022427814521216){.btn .btn-primary}
[Published version (open access)](https://discovery.ucl.ac.uk/id/eprint/1419581/){.btn .btn-primary}

To test the commonly espoused but little examined hypothesis that fluctuations in the price of metal are associated with changes in the volume of metal theft. Specifically, we analyze the relationship between the price of copper and the number of police recorded “live” copper cable thefts from the British railway network (2006 to 2012). Time-series analysis was performed using 76 months of data to determine the association between mean copper price and police recorded “live” copper cable theft. Two rival hypotheses, that changes in the theft of copper cabling reflect changes in the theft of railway property more generally (or the reporting thereof) or variations in the rate of unemployment, were also tested. We find support for the price–theft hypothesis: Changes in the price of copper were positively associated with variations in the volume of “live” copper cable theft. A downward trend in copper cable theft in recent years is also observed, although the mechanism/mechanisms underpinning this pattern is unclear. The theft of “live” copper cable is associated with fluctuations in copper price. As such, it differs substantially from the “crime drop” typically noted for most types of crime providing further support for the price–theft hypothesis.
