---
title: "Does a good cop really never get wet? The impact of weather on stop and frisk"
date: "2018-07-28"
---

Citation: M Ashby, L Tompson. 2018. Does a good cop really never get wet? The impact of weather on stop and frisk. Preprint.

[Preprint](https://osf.io/preprints/socarxiv/au8es/){.btn .btn-primary}
[Materials](https://osf.io/rn9yj/){.btn .btn-primary}

The study of discretionary police activity has largely focused on the demographic characteristics (particularly ethnicity) of the parties involved. This study proposes a police action model that facilitates a more-holistic analysis of individual and situational influences on police actions. This model is used to generate hypotheses about the relationship between police stop and search/frisk and weather (temperature and precipitation) in London and New York City. After controlling for other situational factors (such as public holidays and special events) and for the frequency of street crime, increasing temperatures are associated with small increases in police stops, while precipitation (rain and snow) is associated with substantial decreases. These relationships disappear, however, when stops conducted indoors (e.g. in shopping malls) are modeled. This research suggests that analysis of discretionary police activity should consider the influence of the environment as well as other factors.

