---
title: "Is metal theft committed by organized crime groups, and why does it matter?"
date: "2015-09-03"
---

Citation: M Ashby. 2015. Is metal theft committed by organized crime groups, and why does it matter? _Criminology and Criminal Justice_ 16(2):141--157.

[Published version (open access)](http://doi.org/10.1177/1748895815603777){.btn .btn-primary}
[Postprint](http://irep.ntu.ac.uk/id/eprint/23398/){.btn .btn-primary}

Using the example of metal theft in the United Kingdom, this study used mixed methods to evaluate the accuracy of police estimates of the involvement of organized crime groups (OCGs) in crime. Police estimate that 20–30 per cent of metal theft is committed by OCGs, but this study found that only 0.5 per cent of metal thieves had previous convictions for offences related to OCGs, that only 1.3 per cent were linked to OCGs by intelligence information, that metal thieves typically offended close to their homes and that almost no metal thefts involved sophisticated offence methods. It appears that police may over-estimate the involvement of OCGs in some types of crime. The reasons for and consequences of this over-estimation are discussed.
