---
title: "Understanding changing demand for police during Covid-19"
date: "2021-12-01"
---

Citation: R Solymosi, M Ashby, N Kennar, E Kim, K Byrom, A McMillan, P Liebelt. 2021. _Understanding changing demand for police during Covid-19_. Report for the N8 Policing Research Partnership.

[Published version (open access)](https://www.n8prp.org.uk/wp-content/uploads/sites/315/2022/01/Reka-Solymosi-Police-Demand-Covid.pdf){.btn .btn-primary}
[Project](https://www.n8prp.org.uk/home/research/small-grants/changing-demand-for-police-during-covid-19/){.btn .btn-primary}

Covid-19 has created unprecedented challenges for policing in the UK and globally, both by creating new tasks (e.g. enforcing government restrictions or shielding vulnerable staff), and by shifting patterns in demand resulting from changes in people’s routine activities. There has been some work both in-house and academic, looking at some of these shifts, however these either focus only on crimes, and/or calculate changes by comparing the time period in question to the same time last year, a technique which can provide incorrect and misleading results.  In this project we use a mixed-method approach of robust time-series analysis and qualitative interviews with force call centre staff in a UK police force to explore changes in police demand during the different stages of lockdown.
