---
title: "Forty years of problem-oriented policing: A review of progress in England and Wales"
date: "2021-12-20"
---

Citation: K Bullock, A Sidebottom, R Armitage, M Ashby, C Clemmow, S Kirby, G Laycock, N Tilley. 2021. Forty years of problem-oriented policing: A review of progress in England and Wales. _Policing: A Journal of Policy and Practice_ 15(4):2001--2014.

[Published version (open access)](https://doi.org/10.1093/police/paab067){.btn .btn-primary}

This article analyses and critically reflects on the position of problem-oriented policing within England and Wales. Problem-oriented policing is a framework for improving police effectiveness. Its adoption has consistently been shown to be associated with sizable reductions in a wide range of crimes and public safety issues. However, many studies also find that problem-oriented policing is difficult to embed and sustain within police organisations. This article draws on the experiences and perspectives of 86 informed stakeholders to critically examine the position and practice of problem-oriented policing 40 years after its original formulation by Herman Goldstein in 1979. We argue that despite evidence of renewed interest in problem-oriented policing, the approach is not habitually conducted within police organisations in England and Wales. Where it is conducted, the practice of problem-oriented policing is found to lack discipline, the processes tend not to be faithfully followed, and there are weaknesses at all stages of the process. Implications of the findings for future research and police practice are discussed.
